competition-id: 61226a37683d6d0ef755c5b7
Ocp-Apim-Subscription-Key: ff339f2b511144a8aa85dc8892efbd16
cloud-53-login: admin
cloud-53-password: pass01
cloud-53-base-url: 'https://cloud53-dev-apim.azure-api.net/cloud53-dev/v210821'
default-ping-count: 3
default-sleep-timer: 10
external-host-ip: 1.1.1.1
web-53-auth: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjk2ODQyMjYsIm5iZiI6MTYyOTY0ODIyNiwic3ViIjoiYWRtaW4ifQ.EHFbG0qxaLvf4b0hiEwubf2qTFMiUzYkBoYROCemwhg'
linux-ping-parser: 2>&1 | awk -F'/' 'END{ print (/^rtt/? "OK "$5" ms":"FAIL") }'
skip_connections:
  - dummy